blank_issues_enabled: false
contact_links:
  - name: LaunchBox Plugin API docs
    url: https://pluginapi.launchbox-app.com
    about: For general LaunchBox plugin API questions (not Loadarr-specific).
